config/routes.rb
Rails.application.routes.draw do
 
  
  root 'pages#landing_page'
  get '/landing_page' => 'pages#landing_page'
  get '/o_nama' => 'pages#o_nama'
  get '/rezervisi' => 'pages#rezervisi'
  get '/rezervisi1' => 'pages#rezervisi1'
  get '/rezervisi2' => 'pages#rezervisi2'
  get '/kontakt' => 'pages#kontakt'
  get '/tereni' => 'pages#tereni'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def landing_page

    
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Termini</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  </head>

  <body>
  <div class="container">

    <%= yield %>

    </div>

  </body>
</html>

app/views/pages/kontakt.html.erb
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3"> <center> TERMINI.BA </center> </h1>
      </header>

<br>
<br>
<br>
<br>

<div class="container">
  
  <div class="document">
    
    <h1>KONTAKT</h1>
    
    <hr class="brace">
    
    <div class="document__content">
      
      <p>t + 387 33 557 910</p>

      <p>t + 387 33 557 913</p>
      
      <p>kontakt@termini.ba,
      armin@termini.ba</p>
      
      <p>Ul. Musala 5
      71000 Sarajevo
      Bosna i Hercegovina</p>
      
    </div>
    
  </div>
  
</div>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>
  
</html>

app/views/pages/landing_page.html.erb
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class ="nav-link" href="%= o_nama_path %">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="%= tereni_path %">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="%= kontakt_path %">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3"> <center> TERMINI.BA </center> </h1>
      </header>

      <!-- Page Features -->
      <div class="row text-center">

        <div class="col-lg-4 col-md-5 mb-4">
          <div class="card">
            <img class="card-img-top" src="VISTAFON.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">VISTAFON</h4>
              <p class="card-text">Lokacija: Otoka</p>
              <p class="card-text">Adresa: Bulevar Meše Selimovića, Sarajevo </p>
              <p class="card-text">Radno vrijeme : 07-22</p>
            </div>
            <div class="card-footer">
              <a href="<%= rezervisi2_path %>" class="btn btn-primary">REZERVIŠI!</a>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-5 mb-4">
          <div class="card">
            <img class="card-img-top" src="MOJMILO.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">DVORANA RAMIZ SALICIN</h4>
              <p class="card-text">Lokacija: Mojmilo</p>
              <p class="card-text">Adresa: Semira Frašte 21, Sarajevo</p>
              <p class="card-text">Radno vrijeme : 07-22</p>
            </div>
            <div class="card-footer">
              <a href="<%= rezervisi1_path %>"" class="btn btn-primary">REZERVIŠI!</a>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-5 mb-4">
          <div class="card">
            <img class="card-img-top" id="myBtn" src="GRBAVICA.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">DVORANA GRBAVICA</h4>
              <p class="card-text">Lokacija: Grbavica</p>
              <p class="card-text">Adresa : Zvornička  277 ,bb  Sarajevo 71000</p>
              <p class="card-text">Radno vrijeme : 07-22</p>
            </div>
            <div class="card-footer">
              <a href="<%= rezervisi_path %>" class="btn btn-primary">REZERVIŠI!</a>
            </div>
          </div>
        </div>

        

      </div>
      <!-- /.row -->

      

      <br>
      <br>
      <br>
      <br>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

  


  <!-- The Modal -->
  <div id="myModal" class="modal">
  
    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <p>Cijena 80KM</p>
  
    </div>
  
  </div>


</html>






<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
</style>

app/views/pages/o_nama.html.erb
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3"> <center> TERMINI.BA </center> </h1>
      </header>

<br>
<br>
<div class="container">
  
  <div class="document">
    
    <h1>O NAMA</h1>
    
    <hr class="brace">
    
    <div class="document__content">
      
      <p> Neka vaš marketing bude u našim rukama. Oglasite se još danas po povoljnoj cijeni i vaše sale za termine će biti prepune svakim danima. Powered by Krule, Mirza i Nijaz</p>

    
      
    </div>
    
  </div>
  
</div>




<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

  
</html>

app/views/pages/rezervisi.html.erb
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <br>
<br>
<br>
<br>
<br>
<h1 class="deepshd"> RASPORED </h1>
<br>

<div class="container">
  <button type="button" class="btn btn-primary">Slobodno <span class="badge"></span></button>   
  <button type="button" class="btn btn-danger">Zauzeto <span class="badge"></span></button>        
</div>

<br>

    <img class="card-img-top" id="myBtn" src="RASPORED.jpg" alt="">


    
<br><br>
<div class="container">
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">REZERVIŠI</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
     
        <h4 class="modal-title">033 646-470</h4>
      </div>
      <div class="modal-body">
        <p>40KM OD 07-18</p>
        <p>80KM OD 18-22</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">ZATVORI</button>
      </div>
    </div>
  </div>
</div>
</div>

</body>
</html>


<br><br>
   

</div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

  


  <!-- The Modal -->
  <div id="myModal" class="modal">
  
    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <p>Cijena 80KM</p>
  
    </div>
  
  </div>


</html>






<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
</style>

app/views/pages/rezervisi1.html.erb
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <br>
<br>
<br>
<br>
<br>
<h1 class="deepshd"> RASPORED </h1>
<br>

<div class="container">
  <button type="button" class="btn btn-primary">Slobodno <span class="badge"></span></button>   
  <button type="button" class="btn btn-danger">Zauzeto <span class="badge"></span></button>        
</div>

<br>

    <img class="card-img-top" id="myBtn" src="RASPORED.jpg" alt="">


    
<br><br>
<div class="container">
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">REZERVIŠI</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
     
        <h4 class="modal-title">033 467-446</h4>
      </div>
      <div class="modal-body">
        <p>40KM OD 07-18</p>
        <p>70KM OD 18-22</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">ZATVORI</button>
      </div>
    </div>
  </div>
</div>
</div>

</body>
</html>

<br><br>
   

</div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

  


  <!-- The Modal -->
  <div id="myModal" class="modal">
  
    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <p>Cijena 80KM</p>
  
    </div>
  
  </div>


</html>






<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
</style>

app/views/pages/tereni.html.erb
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TERMINI.BA</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">TERMINI.BA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">O NAMA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">TERENI</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">KONTAKT</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3"> <center> TERMINI.BA </center> </h1>
      </header>

<br>
<br>

<br>
<br>
<br>

<div class="container">
  
  <div class="document">
    
    <h1>OSTALI TERENI</h1>
    
    <hr class="brace">
    
    <div class="document__content">
      
      

    
      
    </div>
    
  </div>
  
</div>
<br><br>


<h1 class="xbootstrap">FIS Sarajevo, Sarajevo, Mis Irbina br. 10
</h1>
<h1 class="xbootstrap">
tel:033 268 760 </h1>
<br><br>
<h1 class="xbootstrap">Olimpijska dvorana Zetra, Sarajevo, Branilaca Sarajeva 21
</h1>
<h1 class="xbootstrap">
tel:033 212 018 </h1>
<br><br>
<h1 class="xbootstrap">Sportsko-rekreativni centar HOTONJ - Sporta, Sarajevo, Branilaca Hotonja 196
</h1>
<h1 class="xbootstrap">
tel:061 159 149</h1>
<br><br>
<h1 class="xbootstrap">KSC Ilidža, Sarajevo, Mala aleja 67
</h1>
<h1 class="xbootstrap">
tel:033 636 514</h1>
<br><br>
<h1 class="xbootstrap">Sportska dvorana Dobrinja, Sarajevo, Bulevar branilaca Dobrinje 4-a
</h1>
<h1 class="xbootstrap">
tel: 033 467 751</h1>
<br><br>
<h1 class="xbootstrap">Sportska dvorana Dobrinja, Sarajevo, Bulevar branilaca Dobrinje 4-a
</h1>
<h1 class="xbootstrap">
tel: 033 467 751</h1>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

  
</html>